### ISSUE TITLE
Unable to connect. Skipping bot.

### ISSUE THREAD

**Issue by ameya-joshi-tuc** [farhan3/py-botnet#1]
Hello

I am trying to use this tool for generating botnet communication and am facing issues with the message 'Unable to connect. Skipping bot.' I am running everything inside docker containers (It is a requirement from my end). I tried running everything on one container, as well as different containers but I am still unable to get the communication to run(The containers can ping each other so there is no issue with connectivity). Are there any prerequisite system requirements/library requirements for using these bots? My containers run Ubuntu 14.04.5 LTS. I would be really grateful if you provide some insights as your botnet model is exactly what I need for my university work.

Thank you for your help

**Comment by StealUrBones** [comment]
How did you fix this?
